name: Build and Test

on:
  push:
    branches:
      - main  # Укажите имя вашей основной ветки

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Получение кода
      uses: actions/checkout@v2

    - name: Настройка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run Unit Tests
      run: |
        echo "Running tests..."
        cd my_python_project  # Перейти в директорию с проектом
        python -m unittest discover tests

    - name: Уведомление о сбое
      if: failure()  # Запускать этот шаг только в случае сбоя предыдущего шага (тестов)
      run: |
        echo "Тесты завершились неудачей. Отправка уведомления..."
        pip install python-telegram-bot
        python notify.py  # Это вызывает ваш скрипт notify.py
