name: Test and Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies and run tests
      run: |
        pip install coverage
        python3 -m unittest discover -s . -p '*test*.py' 

    - name: Run tests
      run: python3 -m unittest discover -s . -p '*test*.py'

    - name: Generate coverage report
      run: |
        pip install coverage
        coverage run -m unittest discover -s . -p '*test*.py'
        coverage report -m

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: ./htmlcov

