name: Run Tests and Coverage Check

on:
  push:
    branches:
      - main  # Укажите нужную ветку

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Укажите версию Python, если необходимо

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m unittest discover tests

    - name: Check test coverage
      run: |
        coverage run -m unittest discover tests
        coverage report -m
        coverage html

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov  # Путь к папке с HTML-отчетом

